<?php

namespace App\Models\Concerns;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;

/**
 * Idempotent writes for a client that may retry.
 *
 * This app is used in the field on connections that drop mid-request. When a
 * response is lost the client cannot tell whether the server processed the write
 * or never saw it, so it retries — and without a key of its own that retry
 * becomes a second submission sitting in the review queue, or a duplicate
 * progress report skewing the roll-up.
 *
 * The fix is to let the client name the write. It generates a UUID before the
 * first attempt, stores it with the queued request, and sends the same value on
 * every retry. A unique index turns the second arrival into a no-op that returns
 * the original row, so the client sees success either way.
 *
 * The key must be generated by the client, not the server: it has to survive the
 * app being killed between attempts, which a server-side value never could.
 */
trait HasClientUuid
{
    /**
     * Create a row, or return the one this client already created.
     *
     * The unique index is what actually guarantees uniqueness — the lookup only
     * avoids the common case of doing an insert that is bound to fail. Two
     * requests racing will both pass the lookup, and the loser's duplicate-key
     * error is caught and resolved to the winner's row.
     *
     * @param  array<string, mixed>  $attributes
     */
    public static function createOnce(?string $clientUuid, array $attributes): Model
    {
        if (blank($clientUuid)) {
            return static::create($attributes);
        }

        if ($existing = static::query()->where('client_uuid', $clientUuid)->first()) {
            return $existing;
        }

        try {
            return static::create($attributes + ['client_uuid' => $clientUuid]);
        } catch (\Illuminate\Database\UniqueConstraintViolationException $e) {
            // Lost the race. The winner's row is the correct answer.
            return static::query()->where('client_uuid', $clientUuid)->firstOrFail();
        }
    }

    /**
     * Has this client key already been used?
     *
     * Lets a controller answer a replayed request with 200 and the original
     * resource rather than re-running side effects such as pushes.
     */
    public static function alreadyRecorded(?string $clientUuid): bool
    {
        return filled($clientUuid)
            && static::query()->where('client_uuid', $clientUuid)->exists();
    }

    public function scopeByClientUuid(Builder $query, string $clientUuid): Builder
    {
        return $query->where('client_uuid', $clientUuid);
    }

    /** Rows that came from a device rather than the admin panel. */
    public function scopeFromDevice(Builder $query): Builder
    {
        return $query->whereNotNull('client_uuid');
    }
}
