<?php

namespace App\Filament\Resources\Permissions;

use App\Filament\Resources\Permissions\Pages\ListPermissions;
use App\Support\PermissionCatalog;
use BackedEnum;
use Filament\Resources\Resource;
use Filament\Tables;
use Filament\Tables\Table;
use Spatie\Permission\Models\Permission;

/**
 * Read-only view of the permission vocabulary. Permissions are generated by
 * the seeder from {@see PermissionCatalog}; operators assign them to roles, but
 * never create/edit/delete them here (enforced by {@see \App\Policies\PermissionPolicy}).
 */
class PermissionResource extends Resource
{
    protected static ?string $model = Permission::class;

    protected static string|BackedEnum|null $navigationIcon = 'heroicon-o-key';

    protected static string|\UnitEnum|null $navigationGroup = 'Access Control';

    protected static ?string $navigationLabel = 'Permissions';

    protected static ?int $navigationSort = 2;

    protected static ?string $recordTitleAttribute = 'name';

    /**
     * Reverse index: permission name => UI group label. Built once from the
     * catalog so the table can show which module each permission belongs to.
     *
     * @return array<string, string>
     */
    protected static function groupIndex(): array
    {
        static $index = null;

        if ($index === null) {
            $index = [];
            foreach (PermissionCatalog::groupedForUi() as $group => $permissions) {
                foreach (array_keys($permissions) as $name) {
                    $index[$name] = $group;
                }
            }
        }

        return $index;
    }

    public static function table(Table $table): Table
    {
        return $table
            ->columns([
                Tables\Columns\TextColumn::make('name')
                    ->searchable()
                    ->sortable()
                    ->copyable(),
                Tables\Columns\TextColumn::make('group')
                    ->label('Module / area')
                    ->badge()
                    ->getStateUsing(fn (Permission $record): string => static::groupIndex()[$record->name] ?? 'Uncategorised')
                    ->sortable(),
                Tables\Columns\TextColumn::make('roles_count')
                    ->label('Used by roles')
                    ->counts('roles')
                    ->badge()
                    ->color('gray'),
                Tables\Columns\TextColumn::make('guard_name')
                    ->label('Guard')
                    ->toggleable(isToggledHiddenByDefault: true),
            ])
            ->defaultSort('name')
            // Read-only: no create/edit/delete actions are registered.
            ->recordActions([])
            ->toolbarActions([]);
    }

    public static function getPages(): array
    {
        return [
            'index' => ListPermissions::route('/'),
        ];
    }
}
