<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

/**
 * Module B — Maintenance visits.
 *
 * A follow-up inspection logged against an existing planting event. Each visit
 * records how many trees were checked and how many were lost since the last
 * look; the event's aggregate `trees_lost` — and therefore its survival rate —
 * is recomputed from the approved visits (see
 * {@see \App\Http\Controllers\Api\MaintenanceVisitController}).
 *
 * Held for review like a planted tree: created `pending`, and only an approved
 * visit is allowed to move the event's numbers. Captured in the field, so it
 * carries the same GPS-and-idempotency baggage as the rest of Module B.
 */
return new class extends Migration
{
    public function up(): void
    {
        Schema::create('maintenance_visits', function (Blueprint $table) {
            $table->id();

            // The idempotency key, generated by the device before the first
            // attempt so an offline replay cannot double-log a visit.
            $table->uuid('client_uuid')->nullable()->unique();

            $table->foreignId('event_id')->constrained()->cascadeOnDelete();
            // Who logged it. Kept if the account is later removed — the visit is
            // programme data, not personal data.
            $table->foreignId('user_id')->nullable()->nullOnDelete();

            $table->date('visit_date');
            // How many trees were inspected, and how many were found dead/lost
            // since the previous visit. `trees_lost` is what feeds survival.
            $table->unsignedInteger('trees_checked')->nullable();
            $table->unsignedInteger('trees_lost')->default(0);
            $table->text('notes')->nullable();

            // Proof of presence — where the inspector stood.
            $table->decimal('latitude', 10, 7)->nullable();
            $table->decimal('longitude', 10, 7)->nullable();
            $table->unsignedInteger('gps_accuracy')->nullable();
            $table->string('address')->nullable();
            $table->boolean('is_mocked')->nullable();

            // pending | approved | rejected
            $table->string('status')->default('pending');
            $table->string('rejection_reason')->nullable();
            $table->timestamp('approved_at')->nullable();

            $table->timestamps();

            $table->index(['event_id', 'status']);
        });
    }

    public function down(): void
    {
        Schema::dropIfExists('maintenance_visits');
    }
};
